FROM nvcr.io/nvidia/pytorch:24.05-py3

# Regrouper les désinstallations et installations dans une seule instruction RUN
RUN pip3 uninstall -y \
        pytorch-quantization \
        pytorch-triton \
        torch \
        torch-tensorrt \
        torchvision \
        xgboost transformer_engine flash_attn \
        apex megatron-core && \
    pip3 install torch==2.4.0 torchvision==0.19.0 torchaudio==2.4.0 --index-url https://download.pytorch.org/whl/cu124 && \
    pip3 install --no-cache-dir \
        "torch==2.4.0" \
        accelerate \
        codetiming \
        datasets \
        dill \
        hydra-core \
        numpy \
        pybind11 \
        tensordict \
        "transformers<=4.46.0" \
        vllm==0.6.3 \
        flash-attn==2.7.0.post2 && \
    MAX_JOBS=4 pip3 install -v --disable-pip-version-check --no-cache-dir --no-build-isolation \
        --config-settings "--build-option=--cpp_ext" --config-settings "--build-option=--cuda_ext" \
        git+https://github.com/NVIDIA/apex && \
    MAX_JOBS=4 NINJA_FLAGS="-j4" pip3 install --no-cache-dir --no-build-isolation \
        flash-attn==2.5.8 \
        git+https://github.com/NVIDIA/TransformerEngine.git@v1.7 && \
    pip3 install --no-cache-dir wandb==0.18.7 py-spy

# Nettoyage des caches pour réduire la taille finale de l'image
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
